export declare const branchStyle: string;
export declare const selectedHeaderStyle: string;
export declare const unSelectedHeaderStyle: string;
export declare const smallBranchStyle: string;
export declare const expandedBranchStyle: string;
export declare const openHistorySideBarButtonStyle: string;
export declare const historyLabelStyle: string;
export declare const branchLabelStyle: string;
export declare const branchTrackingLabelStyle: string;
export declare const branchIconStyle: string;
export declare const branchDropdownStyle: string;
export declare const headerButtonStyle: string;
export declare function branchDropdownButtonStyle(isLight: string): string;
export declare function newBranchButtonStyle(isLight: string): string;
export declare const branchTrackingIconStyle: string;
export declare const headerButtonDisabledStyle: string;
export declare const branchListItemStyle: string;
export declare const stagedCommitButtonStyle: string;
export declare const stagedCommitButtonReadyStyle: string;
export declare const stagedCommitButtonDisabledStyle: string;
export declare const textInputStyle: string;
export declare const stagedCommitStyle: string;
export declare const stagedCommitMessageStyle: string;
export declare const branchHeaderCenterContent: string;
