export declare const commitStyle: string;
export declare const headerStyle: string;
export declare const floatRightStyle: string;
export declare const commitOverviewNumbers: string;
export declare const commitDetailStyle: string;
export declare const commitDetailHeader: string;
export declare const commitDetailFileStyle: string;
export declare const commitDetailFilePathStyle: string;
export declare const iconStyle: string;
export declare const numberofChangedFilesStyle: string;
export declare function insertionIconStyle(isLight: string): string;
export declare function deletionIconStyle(isLight: string): string;
export declare function revertButtonStyle(isLight: string): string;
export declare const numberOfDeletionsStyle: string;
export declare const numberOfInsertionsStyle: string;
export declare const WarningLabel: string;
export declare const MessageInput: string;
export declare const Button: string;
export declare const ResetDeleteDisabledButton: string;
export declare const ResetDeleteButton: string;
export declare const CancelButton: string;
