export declare function moveFileUpButtonStyle(isLight: string): string;
export declare function moveFileDownButtonStyle(isLight: string): string;
export declare const moveFileUpButtonSelectedStyle: string;
export declare const moveFileDownButtonSelectedStyle: string;
export declare const notebookFileIconStyle: string;
export declare const consoleFileIconStyle: string;
export declare const terminalFileIconStyle: string;
export declare const folderFileIconStyle: string;
export declare const genericFileIconStyle: string;
export declare const yamlFileIconStyle: string;
export declare const markdownFileIconStyle: string;
export declare const imageFileIconStyle: string;
export declare const spreadsheetFileIconStyle: string;
export declare const jsonFileIconStyle: string;
export declare const pythonFileIconStyle: string;
export declare const kernelFileIconStyle: string;
export declare const notebookFileIconSelectedStyle: string;
export declare const consoleFileIconSelectedStyle: string;
export declare const terminalFileIconSelectedStyle: string;
export declare const folderFileIconSelectedStyle: string;
export declare const genericFileIconSelectedStyle: string;
export declare const yamlFileIconSelectedStyle: string;
export declare const markdownFileIconSelectedStyle: string;
export declare const imageFileIconSelectedStyle: string;
export declare const spreadsheetFileIconSelectedStyle: string;
export declare const jsonFileIconSelectedStyle: string;
export declare const pythonFileIconSelectedStyle: string;
export declare const kernelFileIconSelectedStyle: string;
